# Generated by Django 5.2.6 on 2025-09-23 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(editable=False, unique=True)),
                ('signature_id', models.UUIDField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed')], default='pending', max_length=20)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='api.signature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
