# Generated by Django 5.2.6 on 2025-09-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='signer_url',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
