# Generated by Django 5.2.6 on 2025-09-24 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_signer_signer_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signature',
            name='polling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signature',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='signer',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='api.signature'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='signer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
